-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoIDWXwirLVteOoxg
1jrJavqYhNh2IMuz1GeGh7f/1dmgCgYIKoZIzj0DAQehRANCAARte35FPHf/gpkM
5oI9fQm65Xql/lQ3Zjh0OlufbGbMAFzBWoT3ckcw5FOfpqg0cGHrUAWEXZn2j2GJ
/raSIRLI
-----END PRIVATE KEY-----